services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql

    healthcheck:
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -p${DB_ROOT_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy

  master-data-service:
    build:
      context: ./services/master-data-service
      dockerfile: Dockerfile

    ports:
      - "8001:8001"

    env_file:
      - .env

    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      - ./services/master-data-service:/app

  case-integration-service:
    build:
      context: ./services/case-integration-service
      dockerfile: Dockerfile

    ports:
      - "8002:8002"

    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      - ./services/case-integration-service:/app

  analytics-service:
    build:
      context: ./services/analytics-service
    container_name: janswasthya-analytics-service
    environment:
      DB_USER: ${DB_USER:-janswasthya_user}
      DB_PASSWORD: ${DB_PASSWORD:-janswasthya_pass}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-janswasthya}
    ports:
      - "8003:8003"
    depends_on:
      - mariadb

  mock-provider-system:
    build:
      context: ./mock-systems/mock-provider-system
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./mock-systems/mock-provider-system:/app

  integration-worker:
    build:
      context: ./workers/integration-worker
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PROVIDER_BASE_URL=http://mock-provider-system:9000
      - ANALYTICS_SERVICE_URL=http://analytics-service:8003
      - POLL_INTERVAL_SECONDS=3
      - MAX_RETRIES=3
    depends_on:
      mariadb:
        condition: service_healthy
      mock-provider-system:
        condition: service_started
    volumes:
      - ./workers/integration-worker:/app

volumes:
  mariadb_data:

