"""create healthcare case fact

Revision ID: b8b6e31bf5a3
Revises: 
Create Date: 2026-09-13 12:22:40.066262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b6e31bf5a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_case_fact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_reference_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('case_created_at', sa.DateTime(), nullable=False),
    sa.Column('case_updated_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_case_fact_case_reference_id'), 'healthcare_case_fact', ['case_reference_id'], unique=True)
    op.create_index(op.f('ix_healthcare_case_fact_hospital_id'), 'healthcare_case_fact', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_healthcare_case_fact_service_code'), 'healthcare_case_fact', ['service_code'], unique=False)
    op.create_index(op.f('ix_healthcare_case_fact_status'), 'healthcare_case_fact', ['status'], unique=False)
    op.create_index(op.f('ix_healthcare_case_fact_tenant_id'), 'healthcare_case_fact', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthcare_case_fact_tenant_id'), table_name='healthcare_case_fact')
    op.drop_index(op.f('ix_healthcare_case_fact_status'), table_name='healthcare_case_fact')
    op.drop_index(op.f('ix_healthcare_case_fact_service_code'), table_name='healthcare_case_fact')
    op.drop_index(op.f('ix_healthcare_case_fact_hospital_id'), table_name='healthcare_case_fact')
    op.drop_index(op.f('ix_healthcare_case_fact_case_reference_id'), table_name='healthcare_case_fact')
    op.drop_table('healthcare_case_fact')
    # ### end Alembic commands ###
