"""add outbox and reliability tables

Revision ID: 0e943d03e523
Revises: f7629d3baf9f
Create Date: 2026-09-13 09:39:43.918874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e943d03e523'
down_revision: Union[str, None] = 'f7629d3baf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('original_payload', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('replayed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_message_correlation_id'), 'dead_letter_message', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_message_tenant_id'), 'dead_letter_message', ['tenant_id'], unique=False)
    op.create_table('integration_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('target_system', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_message_correlation_id'), 'integration_message', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_integration_message_status'), 'integration_message', ['status'], unique=False)
    op.create_index(op.f('ix_integration_message_tenant_id'), 'integration_message', ['tenant_id'], unique=False)
    op.create_table('outbox_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_event_aggregate_id'), 'outbox_event', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_event_correlation_id'), 'outbox_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_event_status'), 'outbox_event', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_event_tenant_id'), 'outbox_event', ['tenant_id'], unique=False)
    op.create_table('integration_attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['integration_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_attempt_message_id'), 'integration_attempt', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_attempt_message_id'), table_name='integration_attempt')
    op.drop_table('integration_attempt')
    op.drop_index(op.f('ix_outbox_event_tenant_id'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_status'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_correlation_id'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_aggregate_id'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_index(op.f('ix_integration_message_tenant_id'), table_name='integration_message')
    op.drop_index(op.f('ix_integration_message_status'), table_name='integration_message')
    op.drop_index(op.f('ix_integration_message_correlation_id'), table_name='integration_message')
    op.drop_table('integration_message')
    op.drop_index(op.f('ix_dead_letter_message_tenant_id'), table_name='dead_letter_message')
    op.drop_index(op.f('ix_dead_letter_message_correlation_id'), table_name='dead_letter_message')
    op.drop_table('dead_letter_message')
    # ### end Alembic commands ###
