"""add case_reference and idempotency_record tables

Revision ID: f7629d3baf9f
Revises: 2a5d2593a683
Create Date: 2026-09-13 06:12:18.870144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7629d3baf9f'
down_revision: Union[str, None] = '2a5d2593a683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_record_key'), 'idempotency_record', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_record_tenant_id'), 'idempotency_record', ['tenant_id'], unique=False)
    op.create_table('case_reference',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('servicenow_sys_id', sa.String(length=32), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['hospital_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reference_case_number'), 'case_reference', ['case_number'], unique=True)
    op.create_index(op.f('ix_case_reference_correlation_id'), 'case_reference', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_case_reference_servicenow_sys_id'), 'case_reference', ['servicenow_sys_id'], unique=False)
    op.create_index(op.f('ix_case_reference_tenant_id'), 'case_reference', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_reference_tenant_id'), table_name='case_reference')
    op.drop_index(op.f('ix_case_reference_servicenow_sys_id'), table_name='case_reference')
    op.drop_index(op.f('ix_case_reference_correlation_id'), table_name='case_reference')
    op.drop_index(op.f('ix_case_reference_case_number'), table_name='case_reference')
    op.drop_table('case_reference')
    op.drop_index(op.f('ix_idempotency_record_tenant_id'), table_name='idempotency_record')
    op.drop_index(op.f('ix_idempotency_record_key'), table_name='idempotency_record')
    op.drop_table('idempotency_record')
    # ### end Alembic commands ###
